export default function Terms() {
  return (
    <main className="prose-page">
      <h1>Terms of Service</h1>
      <p className="prose-meta">Last updated: [26/09/2026]</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By accessing or using Nyaya (the "Service"), you agree to these Terms of Service. If you do not agree, please do not use the Service.</p>

      <h2>2. Not Legal Advice</h2>
      <p>
        <strong>Nyaya is an educational and informational research tool. It does not provide
        legal advice, and using it does not create an attorney-client relationship of any
        kind.</strong> Answers are generated by an AI system based on retrieved excerpts of real
        judgments, and may be incomplete, out of date, or occasionally inaccurate. Always verify
        any information against the original judgment and consult a qualified, licensed advocate
        before making any legal decision.
      </p>

      <h2>3. No Warranty</h2>
      <p>
        The Service is provided "as is" and "as available," without warranties of any kind,
        express or implied, including but not limited to accuracy, completeness, or fitness for
        a particular purpose.
      </p>

      <h2>4. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Nyaya and its creator shall not be liable for
        any damages arising from your use of, or reliance on, the Service, including any
        decisions made based on its output.
      </p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose</li>
        <li>Attempt to disrupt, overload, or reverse-engineer the Service</li>
        <li>Misrepresent AI-generated answers as verified legal advice to third parties</li>
      </ul>

      <h2>6. Intellectual Property</h2>
      <p>
        The underlying judgment data is sourced from a public, CC-BY-4.0 licensed government
        dataset. The Nyaya name, design, and original site content are the property of their
        creator. AI-generated answers are provided for your personal, non-commercial research
        use.
      </p>

      <h2>7. Third-Party Services</h2>
      <p>
        The Service relies on third-party infrastructure (including Anthropic, Google Cloud,
        Vercel, and Qdrant). We are not responsible for outages or issues originating from
        these providers.
      </p>

      <h2>8. Changes to the Service or Terms</h2>
      <p>We may modify or discontinue the Service, or update these Terms, at any time without prior notice.</p>

      <h2>9. Governing Law</h2>
      <p>These Terms are governed by the laws of India, without regard to conflict of law principles.</p>

      <h2>10. Contact</h2>
      <p>Questions about these Terms can be directed to: [kanavkedia060@gmail.com]</p>
    </main>
  );
}
