import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  Table, TableRow, TableCell, WidthType, BorderStyle,
} from "docx";

/** Splits a line like "Some **bold** text" into TextRuns with bold applied
 * where ** markers appear. Keeps things simple -- handles bold only, which
 * covers the vast majority of what Claude's answers actually use. */
function parseInlineRuns(text) {
  const parts = text.split(/(\*\*[^*]+\*\*)/g).filter(Boolean);
  return parts.map((part) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return new TextRun({ text: part.slice(2, -2), bold: true });
    }
    return new TextRun(part);
  });
}

function parseMarkdownToDocxChildren(markdown) {
  const lines = markdown.split("\n");
  const children = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      i++;
      continue;
    }

    // Headings
    if (trimmed.startsWith("### ")) {
      children.push(new Paragraph({ text: trimmed.slice(4), heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 100 } }));
      i++;
      continue;
    }
    if (trimmed.startsWith("## ")) {
      children.push(new Paragraph({ text: trimmed.slice(3), heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 } }));
      i++;
      continue;
    }
    if (trimmed.startsWith("# ")) {
      children.push(new Paragraph({ text: trimmed.slice(2), heading: HeadingLevel.HEADING_1, spacing: { before: 280, after: 140 } }));
      i++;
      continue;
    }

    // A markdown table: a header row, a separator row (---), then data rows
    if (trimmed.startsWith("|") && lines[i + 1] && lines[i + 1].trim().match(/^\|[\s:-]+\|/)) {
      const tableLines = [trimmed];
      let j = i + 2; // skip the separator row
      while (j < lines.length && lines[j].trim().startsWith("|")) {
        tableLines.push(lines[j].trim());
        j++;
      }
      const headerCells = tableLines[0].split("|").map((c) => c.trim()).filter((c) => c !== "");
      const rows = [headerCells, ...tableLines.slice(1).map((l) => l.split("|").map((c) => c.trim()).filter((c) => c !== ""))];

      children.push(new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: rows.map((cells, rowIndex) => new TableRow({
          children: cells.map((cellText) => new TableCell({
            width: { size: 100 / cells.length, type: WidthType.PERCENTAGE },
            borders: {
              top: { style: BorderStyle.SINGLE, size: 2, color: "AAAAAA" },
              bottom: { style: BorderStyle.SINGLE, size: 2, color: "AAAAAA" },
              left: { style: BorderStyle.SINGLE, size: 2, color: "AAAAAA" },
              right: { style: BorderStyle.SINGLE, size: 2, color: "AAAAAA" },
            },
            children: [new Paragraph({
              children: [new TextRun({ text: cellText, bold: rowIndex === 0 })],
            })],
          })),
        })),
      }));
      children.push(new Paragraph({ text: "", spacing: { after: 160 } }));
      i = j;
      continue;
    }

    // Bullet list items
    if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      children.push(new Paragraph({
        children: parseInlineRuns(trimmed.slice(2)),
        bullet: { level: 0 },
        spacing: { after: 60 },
      }));
      i++;
      continue;
    }

    // Numbered list items (keep the original "1." etc as plain text -- simple and reliable)
    if (/^\d+\.\s/.test(trimmed)) {
      children.push(new Paragraph({
        children: parseInlineRuns(trimmed),
        indent: { left: 360 },
        spacing: { after: 60 },
      }));
      i++;
      continue;
    }

    // A blockquote-ish line starting with a quote mark, or just a normal paragraph
    children.push(new Paragraph({
      children: parseInlineRuns(trimmed),
      spacing: { after: 140 },
    }));
    i++;
  }

  return children;
}

/**
 * Builds and downloads a .docx file from a title, a markdown body (Claude's
 * answer or brief), and an optional list of sources. Runs entirely in the
 * browser -- nothing is sent to any server.
 */
export async function exportToWord({ title, markdown, sources = [], filename = "nyaya-export.docx" }) {
  const children = [
    new Paragraph({ text: title, heading: HeadingLevel.TITLE, spacing: { after: 200 } }),
    new Paragraph({
      children: [new TextRun({ text: "Generated by Nyaya \u2014 for educational research, not legal advice.", italics: true, color: "888888" })],
      spacing: { after: 300 },
    }),
    ...parseMarkdownToDocxChildren(markdown),
  ];

  if (sources.length > 0) {
    children.push(new Paragraph({ text: "Sources", heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 120 } }));
    sources.forEach((s) => {
      children.push(new Paragraph({
        children: [
          new TextRun({ text: `${s.title} `, bold: true }),
          new TextRun({ text: s.citation ? `(${s.citation})` : "" }),
        ],
        spacing: { after: 80 },
      }));
    });
  }

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
